### PR TITLE
Add ability for profileData to have multiple Reynolds numbers

### PR DESCRIPTION
**Pull request by andersgoude**
added code for interpolating profile coordinates from tabular data with both Reynolds number and angle of attack

### CODE REVIEW

**Comment by petebachant** [comment]
Relevant to #166.

**Comment by petebachant** [comment]
Also relevant to #169. @andersgoude, are any of the interpolation functions you created also present in https://github.com/OpenFOAM/OpenFOAM-dev/tree/master/src/OpenFOAM/interpolations? If so, we should use those instead.

**Comment by andersgoude** [comment]
InterpolateXY is quite similar to interpolate1d, with the difference that interpolateXY is built with fields, while interpolate1d uses lists. Also, interpolate1d is built with binary search for finding the correct index, while interpolateXY uses linear search.

For 2d interpolation, the differences are quite significant.

The other two search functions I included are mainly used for internal purposes

**Comment by petebachant** [comment]
Alright, let's keep them in there. They should probably be moved into `src/interpolations` to mirror how OpenFOAM itself is structured. I don't know if `wmake` can look "up" a directory, however. Maybe it will need to be a shared lib that is compiled first?

Similarly, in general, code style should follow [OpenFOAM's style guide](http://www.openfoam.org/contrib/code-style.php). Some things off the top of my head:

* `size_t` --> `label`
* `double` --> `scalar`
* `char` or `std::string` --> `word`
* Line lengths below 80 characters

**Comment by petebachant** [comment]
Thinking maybe the dictionary entries could look like 

Single Reynolds number usage (present):
```c++
profileData
{
    Re 1e6; // Would be list if multiple Re, could be "none" to turn off Re corrections, 
            // or if omitted would be assumed to be none
    data
    (
        // alpha_deg cl cd
    );
}
```

Multiple Reynolds number usage:
```c++
profileData
{
    Re (0.5e6 0.7e6 1e6); // Since this is a list, the data entry will be ignored
    liftCoeffData
    (
        // alpha_deg cl_Re0 cl_Re1 cl_Re2
    );
    dragCoeffData
    (
        // alpha_deg cd_Re0 cd_Re1 cd_Re2
    );
    \\ momentCoeffData could be empty or taken from regular data entry? 
}
```

**Comment by andersgoude** [comment]
If it should be supported that moment coefficients are given according to the single Reynolds number format, while lift and drag coefficients are given according to the multiple Reynolds number format, the above input format will not work.

**Comment by petebachant** [comment]
Yeah, I think it should be one or the other, not an exception for the moment coefficient. Unfortunately the Sheldahl and Klimas `cm` data is not tabulated at all Reynolds numbers.

**Pull request merged**
