### PR TITLE
Reynolds number dependent constants for LeishmanBeddoes model that can either precalculated, or given as input

### PR DESCRIPTION
**Pull request by andersgoude**
With the current version, it is possible to set a list of Reynolds number for the Leishman Beddoes coefficients. Data for these coefficients will be computed once, and later interpolated from. It is also possible to give these coefficients manually.

To use the functionality, give the list of Reynolds number among the dynamic stall coefficients according to:
Re          (list of number);

The following constants are affected:
alphaSS, CNAlpha, alpha1, CN1, CD0, S1, S2, K1, K2, and are given as input by giving a list of equal length as Re among the coefficients

### CODE REVIEW

**Comment by petebachant** [comment]
I just merged some commits from your other PR into master and I created some conflicts. Can you merge upstream `master` back into this and #177?

**Comment by petebachant** [comment]
Anders, I think this is due for a merge from `upstream master`. I added some automatic code style checking yesterday. You can run this locally if you install `vera++` (available in Ubuntu repos) and run `./checkStyle`.

**Comment by andersgoude** [comment]
There are some parts of the style that needs clarification: First, according to the OpenFoam code style, for loops can be splitted with each command on a single line, however, the current checks reports this as invalid, as a whitespace is not following for (or it complains about trailing whitespaces). The second part, which I haven't found any details about, is how one should use the for loops in case one of the statements are unnecessary. Right now, it is written as a single ;, which the code check complains about, however, I don't know how it should be written according to the OpenFoam code style

**Comment by petebachant** [comment]
You're right. I have only added some default rules from vera++ thus far: https://bitbucket.org/verateam/vera/wiki/Rules

The "single space after keywords" (rule T008) needs some refinement to allow for multi-line blocks. 

I'm not sure about the second case--could search through OpenFOAM for examples I guess. Rule T007 allows for a blank space between the semicolons:

```c++
for ( ; ; ) // OK as an exception
{
    // ...
}
```

**Comment by andersgoude** [comment]
One other solution for the second case is to write the code with while loops instead...

**Comment by petebachant** [comment]
Sure. I don't want to get too bogged down with style details. Just trying to stay clean and consistent.

**Comment by petebachant** [comment]
Anders, 

Do you have any sample tables for these coefficients (S1, S2, K1, K2) versus Re?

**Comment by andersgoude** [comment]
These are the reynolds number dependent constants used in the Dyachuk model for NACA0021:
ReList (40000,80000,160000,360000,700000,1000000,2000000,5000000);
CNalpha (3.2397,4.7255,5.2274,5.6084,5.8048,5.8904,5.9625,6.2771);
CD0 (0.0232,0.0177,0.0139,0.0111,0.0094,0.0089,0.0082,0.0078);
CN1 (0.34311,0.57438,0.72628,0.87407,0.97478,1.0264,1.1324,1.2367);
alpha1 (7.7466,9.0006,10.2013,11.3078,12.1635,12.6109,13.7035,14.0118);
S1 (0.70707,1.2121,1.8182,2.1212,2.4242,2.5253,2.8283,4.2424);
S2 (1.5152,2.4242,3.7374,5.1515,5.8586,6.1616,6.6667,6.6667);

I don't have any values for K1 and K2, as the model does not contain any implementation of the momentum coefficient

**Comment by petebachant** [comment]
Thanks for this contribution Anders. I have implemented a version where the DS models will use the lists if they're present, and calculate them if not.

**Pull request merged**
